Decompressors::GzipReader: fix open_stream close for nil stream
Otherwise, a failure in opening the stream will cause `gz` to be `nil`,
causing `close` to fail. At the very least, this makes test failures
from register-ingester-oc confusing, since

    #<Double "stream"> received unexpected message :readpartial with (2048)

or

    Zlib::GzipFile::Error: not in gzip format

are reported as failure

    undefined method `close' for nil:NilClass

instead.